name: Build OBS Service Cargo

on: [push, pull_request]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Install Rust
      uses: dtolnay/rust-toolchain@stable
    - name: Install dependencies
      run: |
        sudo apt-get update -y
        sudo apt-get install -y libzstd-dev
    - name: Build
      run: |
        rm Cargo.lock
        cargo build --release --all-features
    - name: Check formatting
      run: |
        cargo fmt -- --check
    - name: Run sample projects to test
      run: |
        chmod +x runtests.sh
        ./runtests.sh
