name: Build OBS Service Cargo

on: [push, pull_request]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    container: opensuse/tumbleweed:latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Install dependencies and Rust
      run: |
        zypper --non-interactive in libzstd-devel rustup
        rustup default stable
        rustup update
    - name: Build
      run: |
        # Disable `cargo update` until a new version of rustsec is being released
        # See: https://github.com/rustsec/rustsec/issues/1130
        # cargo update
        # cargo build --release --all-features 
        cargo build --release --all-features --locked
    - name: Check formatting
      run: |
        cargo fmt -- --check
    - name: Run sample projects to test
      run: |
        chmod +x runtests.sh
        ./runtests.sh
